# src/docs/swagger.yaml
openapi: 3.0.0
info:
  title: Accounting Node TS 
  version: 1.1.0
  description: Swagger docs for my Node TS accounting application.

servers:
  - url: http://localhost:3000

paths:
  /api/users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string

